### ISSUE TITLE
Hardcode Pixel Volcano Dragon's Gem to not be the gem of Pixel Volcano Dragon

### ISSUE THREAD

**Issue by Raijinili** [TsubakiBotPad/pad-data-pipeline#18]
https://github.com/TsubakiBotPad/pad-data-pipeline/blob/4a50f89665327814cdb69081d9255b8117ad7c8f/etl/pad/raw_processor/crossed_data.py#L75-L78

**6254. Pixel Volcano Dragon's Gem** is **5902. Pixel Volcano Dragon**'s evo mat, rather than the result of an exchange (despite having the Gem LS: "A special Evo Material you can obtain through [Monster Exchange]").

**Comment by RheingoldRiver** [comment]
we are not doing this because data is in `exchanges` table
