### ISSUE TITLE
Rebuild Enemy Skills

### ISSUE THREAD

**Issue by loopdeer** [TsubakiBotPad/pad-data-pipeline#185]
Enemy skills need to be rebuilt after fixes are applied to ESBehavior logic.

First run:
``` python rebuild_enemy_skills.py --input [raw_data folder] --output [path]```
You will see 3 folders, behavior_data, behavior_plain, and behavior_text.

Now run data_processor.py making sure to provide --es_dir [path to behavior_data]

A rebuild has to occur in order to further fix up Menoa in shura1 and all the spawns in Mystics and Sceptres.

**Comment by chasehult** [comment]
Done!
