### ISSUE TITLE
Some exchange.py fields

### ISSUE THREAD

**Issue by Raijinili** [TsubakiBotPad/pad-data-pipeline#19]
https://github.com/TsubakiBotPad/pad-data-pipeline/blob/4a50f89665327814cdb69081d9255b8117ad7c8f/etl/pad/raw/exchange.py#L36-L39

[5] is level of the resulting monster.

[6] is bitflags for the resulting monster:
- &1: Max-skilled.
- &2: Max-awoken.

---

https://github.com/TsubakiBotPad/pad-data-pipeline/blob/4a50f89665327814cdb69081d9255b8117ad7c8f/etl/pad/raw/exchange.py#L68-L71
Bitflags.
- &1: No dupes.
- &2: "Restricted"/"One-Time Only!"
- &4: Multiexchange. Brings up the menu where you can exchange up to 30 times at once.

**Comment by RheingoldRiver** [comment]
closed by #16
