### ISSUE TITLE
Super revo sakuya's image is missing her subattribute

### ISSUE THREAD

**Issue by turtleworks** [TsubakiBotPad/pad-data-pipeline#190]
[5393] super revo sakuya was buffed to have a water subattribute, but while it is in her data, it's not in her image.

![image](https://user-images.githubusercontent.com/72906298/123501981-bc32c300-d616-11eb-8912-6b4af2388b36.png)

**Comment by RheingoldRiver** [comment]
![image](https://user-images.githubusercontent.com/18037011/128162203-5869baf0-4c30-4179-b326-fac703c9edfe.png)

![image](https://user-images.githubusercontent.com/18037011/128162246-04a469ce-556b-4f65-8ab2-5dc4ae8cb820.png)
