### ISSUE TITLE
Rewrite image_pull/README.md

### ISSUE THREAD

**Issue by chasehult** [TsubakiBotPad/pad-data-pipeline#214]
The info there is very outdated.  For instance:
> I'm hosting this data on Google Cloud Storage and on Backblaze. The Cloud Storage buckets these are published to is locked down to prevent scraping, and Backblaze isn’t really sync-friendly; contact tactical_retreat if you would like to
sync anything here.

**Comment by RheingoldRiver** [comment]
(actually, make this into a wiki page and have the README point to the wiki page)
