### ISSUE TITLE
Norza's picture & animation are missing several layers

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-data-pipeline#25]
https://d1kpnpud0qoyxf.cloudfront.net/media/animated_portraits/06156.mp4 / https://d1kpnpud0qoyxf.cloudfront.net/media/animated_portraits/06156.gif

as well as in the still: https://d1kpnpud0qoyxf.cloudfront.net/media/portraits/06156.png?cachebuster=2

**Comment by loopdeer** [comment]
Created a PR in pad-resources
