### ISSUE TITLE
Auto transliteration issue with card #6293

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-data-pipeline#28]
No. 6293 One For All, All Might has jp name `「ワン・フォー・オール」オールマイト` and the automatic transliteration of the jp  name is just `fo` which is the part between the dots, `フォー`. Unclear if this is a data issue with this one card and needs to be changed in the crud or a code issue where we have to change handling of special characters for a more general case.

**Comment by dchang0413** [comment]
6299
「ワン・フォー・オール」緑谷出久
6293
「ワン・フォー・オール」オールマイト

both become fo

Problem should be about
「ワン・フォー・オール」
Most likely the bracket since the dot did not bring up any issue with 6323 サー・ナイトアイ

**Comment by RheingoldRiver** [comment]
Closed after moving to right repo
