### ISSUE TITLE
Thanos is in the NA database

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-data-pipeline#452]
![image](https://user-images.githubusercontent.com/18037011/219509196-04d167ca-2e70-4ede-b621-5cba0c202161.png)

**Comment by RheingoldRiver** [comment]
![image](https://user-images.githubusercontent.com/18037011/219524956-8a27c86b-ec21-41c7-af68-e4608938dab1.png)

**Comment by chasehult** [comment]
Fixed! I just deleted him.  He won't repopulate.
