### ISSUE TITLE
Cards that lost row awakenings are showing extra copies of their last super awakening

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-data-pipeline#55]
![image](https://user-images.githubusercontent.com/18037011/102701627-80114680-421e-11eb-8db2-04c59c5d8ea0.png)

Probably extra data is sticking around in the pipeline and needs to be dropped from the awakenings table (or awoken skills? I don't remember which is which gg)

**Comment by Raijinili** [comment]
Rather than outdated data, maybe it's because the JP cards have fewer awakenings than NA cards, which doesn't normally happen.

**Comment by RheingoldRiver** [comment]
Fixed by #56
