### ISSUE TITLE
Max skill level does not match NA version

### ISSUE THREAD

**Issue by ReneRanzinger** [TsubakiBotPad/pad-data-pipeline#57]
That is an ongoing issue I also reported to tactical_retreat previously. The maximum level for skills get changed from time to time. Unfortunately, that is not in sync across the JP, KR and NA version. NA usual gets these changes much later (sometimes months later). Here is a current example (20.12.2020):

Monster 2512 (Snow Star Byakko, Haku) has active skill 634 (Western Seven-Star Formation). In the database "turn_min" is 7 (Skill Level 8). Which is probably true for JP version (and maybe KR) but in the NA version the minimum turn is still 8 (Skill Level 7).

**Comment by RheingoldRiver** [comment]
We only include JP data currently, so this behavior is correct afaik. However see #48 which would have us export two separate copies of all relevant tables. Unless I'm misunderstanding the issue?

**Comment by ReneRanzinger** [comment]
@RheingoldRiver If that "exporting" also refers to the SQLite database, yes that would solve the problem. How would that look like? Separate SQLite exports for NA, JP and KR or additional tables within the database?

**Comment by RheingoldRiver** [comment]
Additional tables within the database, e.g. monsters_na, etc

**Comment by ReneRanzinger** [comment]
@RheingoldRiver Sounds good. In that case I will close this ticket and keep an eye on #48 .
