### ISSUE TITLE
Dungeon names can accidentally have more than one type prefix

### ISSUE THREAD

**Issue by Raijinili** [TsubakiBotPad/pad-data-pipeline#86]
Sometimes, dungeons can have more than one name prefix indicating their type. I think this has only been due to a typo by GHNA.

At one point, dungeon 4407 had this NA name, indicating (twice) that it was a quest dungeon:
`#Q##Q#November Quest Dungeon-Int`

This was eventually fixed, and the name is now:
`#Q#November Quest Dungeon-Int`
There are currently no dungeons with more than one type marker.

If the second marker is not stripped, you store the name as `#Q#November Quest Dungeon-Int`. Not a HUGE deal.

There is one that currently has two identical color markers, but the code doesn't break from it. It will probably be fixed at some point. 
d=4429 f=7: `$47ae64$$47ae64$Kaguya-Hime!-No RCV/Awoken Skills`

The code which handles this:
https://github.com/TsubakiBotPad/pad-data-pipeline/blob/4b02fbbcce7d03781fffe3a590f261adfa2e4725/etl/pad/raw/dungeon.py#L169-L173

**Comment by RheingoldRiver** [comment]
This was resolved at some point
